import type { Metadata } from 'next';

import { inter, manrope } from '@/lib/fonts';

import './globals.css';
import { Header } from '@/components/organisms';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-[#EFEFFF]">
        <Header />
        {children}
        </body>
    </html>
  );
}
