import type { Metadata } from 'next';

import { alexandria, inter, manrope } from '@/lib/fonts';

import './globals.css';
import { Header, Footer } from '@/components/organisms';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${manrope.variable} ${alexandria.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-[#EFEFFF] font-sans">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
